### ISSUE TITLE
GCL Calculator

### ISSUE THREAD

**Issue by webninjasi** [kaganndemirr/IEEE-802-1-Qci#7]
Gate Control List ayarlamak için yardımcı olabilecek hesaplama yöntemleri/araçları bulmak veya yapmak gerekli. Hesaplama araçları host bazında hesaplama yapan standart GCL için ise stream oluşturan applicationları host gibi düşünmek faydalı olabilir.

**Comment by kaganndemirr** [comment]
https://github.com/CoRE-RG/CoRE4INET/tree/master/src/core4inet/linklayer/shaper/IEEE8021Qbv/gate
